### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by CALADARI** [CrackyStudio/arkso#10]
ARKSO crash after i select steamCMD.exe and can not be start again.
Can see ARKSO.exe in TaskManager for few seconds before it disappear.
Is there anyway to fully re-install ARKSO? I think this might be caused by a corrupted configration file.

**Comment by CALADARI** [comment]
Simply delete "C:\Users\your_user_name\AppData\Local\ARK Server Organiser" will fix this.

**Comment by CALADARI** [comment]
Not helping , still crash on first setup and keep crashing after.
Neither install fresh steamCMD via ARKOS  nor select steamCMD.exe existed works.

**Comment by CrackyStudio** [comment]
Could you provide logs from  "C:\Users\your_user_name\AppData\Local\ARK Server Organiser\logs" ?

**Comment by CALADARI** [comment]
Just tried again.
The ARKSO restored somehow…… but before this I've already make server up and running with ArkServerManager.
But anyway I'll attatch log below. But since I've deleted the folder for a few times , I'm not pretty sure it contains logs when issue happens. Hope it helps.
[Logs.txt](https://github.com/CrackyStudio/arkso/files/4271383/Logs.txt)

**Comment by CrackyStudio** [comment]
Thanks for the feedback. There is no trace useful in your logs but I'm glad to see that it works now.
