### ISSUE TITLE
Old ARKSO data detected

### ISSUE THREAD

**Issue by FirnenFR** [CrackyStudio/arkso#17]
I used to make ark servers using arkso on my VPS but now when i lanch arkso the app detects an old steamCMD that doesn't exist anymore 

Is there a way to reset arkso ? (I speak french)

**Comment by FirnenFR** [comment]
okay actually i'm the dumbest man alive

i didn't read the wiki and the answer i was searching was there

**Comment by CrackyStudio** [comment]
Ravi que tu ai pu trouver la réponse à ta question de toi même, ça arrive de ne pas chercher au bon endroit dès le départ ;)
