### ISSUE TITLE
Question Not Issue

### ISSUE THREAD

**Issue by jsmb768ypl** [CrackyStudio/arkso#2]
Is it possible to set this up to run on windows but connect to a steamcmd running on a linux server?

**Comment by CrackyStudio** [comment]
No sorry, it's 100% windows only. But PlayOnLinux or Wine allow windows apps runing on linux, you can try, but I'm not sure it will works.

**Comment by Levvy055** [comment]
it will be possible by ssh for example to run commands on remote server

**Comment by CrackyStudio** [comment]
Not planned now, sorry for late answer.
