### ISSUE TITLE
Window is not draggable

### ISSUE THREAD

**Issue by Elmardus** [CrackyStudio/arkso#5]
The main UI window of ARKSO cannot be dragged around by the top bar, nor be moved using ALT+TAB. 

Tested on: Windows 10 home, build 1903

**Comment by CrackyStudio** [comment]
Yes it's not a bug, it's a desired feature.

**Comment by Elmardus** [comment]
Is it though? On a multi-screen setup it can be inconvenient to not be able to move it to a different monitor.

**Comment by CrackyStudio** [comment]
You're right, it could be a nice enhancement for multi-screen!

**Comment by CrackyStudio** [comment]
This enhancement is ready to use in next release of ARKSO. Development of this feature is done. Coming soon.
