### ISSUE TITLE
Server status stays on 'Starting'

### ISSUE THREAD

**Issue by Elmardus** [CrackyStudio/arkso#6]
After pressing the 'Turn ON' button on the ARKSO screen, the shootergameserver.exe cmd window opens, and the server starts as expected. The server can be joined succesfully. However, the server status on the ARKSO interface is always displayed as 'starting'.

[Screenshot](https://i.imgur.com/cttTeRy.jpg)

**Comment by CrackyStudio** [comment]
Thanks for opening an issue. I still not find a solution. Any tips are welcome.

**Comment by CrackyStudio** [comment]
This issue should be resolved now with version 5.0
