### ISSUE TITLE
Trojan Virus

### ISSUE THREAD

**Issue by Anonymous-Griefer** [CrackyStudio/arkso#7]
File contains a known Trojan virus 

> Occamy.C

Just a warning to have this git re-checked for viruses, thank you.

![WindowsDefenderPreview](https://user-images.githubusercontent.com/12074286/70398601-3119ba00-19eb-11ea-9978-d13a642bc3cd.jpg)

**Comment by CrackyStudio** [comment]
It's a new false positive probably coming with a security update from Microsoft. I'll Ask them one more time to check my app and remove this severe warning. Sorry for the inconvenience.

**Comment by CrackyStudio** [comment]
After some tests, I can confirm that the problem come from the steamcmd.exe file packed in my app. The best solution will be to remove it from solution and download it at first launch.

I'll do an update as soon as possible to fix that. 
Thank you for your patience.

**Comment by CrackyStudio** [comment]
Version 5.0 is now available and undetected.
